### ISSUE TITLE
Feature request: provide option to support texi files directly

### ISSUE THREAD

**Issue by suhail-singh** [magit/sisyphus#1]
Currently if a project has an Org file that gets converted to `.texi`, bumping
version works.  However, if a project doesn't generate `.texi` files via Org
then bumping version doesn't work.

It would help if there were `sisyphus--bump-version-texi` (similar to
`sisyphus--bump-version-org`).  Alternatively, `sisyphus--bump-version-org`
could be changed into `sisyphus--bump-version-docs` where the latter supports
both documentation written in Org or directly in `.texi`.

PS: Thank you for this library.  It has made managing Elisp projects easier.

**Comment by suhail-singh** [comment]
Further, for `.texi` files, I believe it may be sufficient to simply support
"flag variables".  I.e., a regular expression that matches something like below
would work:

```
@set VERSION <version-value-till-end-of-line>
```

**Comment by tarsius** [comment]
For the time being, please implement this in your own friendly fork. I intend to eventually add some functionality that I myself do not need, but it is too early for that -- a lot of functionality that I would need, is still missing. Adding too much (by me) unneeded functionality as soon as it is requested would make it harder to move forward, once I find the time for another push.

I figured from the start, I could use the "do it in your fork" approach for this one package, because its users by definition know how how to write some elisp. I intended to write something a bit more well reasoned than this, the first time someone asks for something that I don't want to add (ever or just yet), but I am currently too busy with other things (as you know :grinning:) to do that just now.
